# Generated by Django 2.2.4 on 2023-08-11 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20230811_2052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='users_buy',
        ),
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='service',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
